import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:speech_to_text/speech_to_text.dart' as stt;
// 💡 IMPORT THE FILE GENERATED BY FLUTTERFIRE:
import 'firebase_options.dart'; 

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    // 💡 CLEAN INITIALIZATION USING YOUR NATIVE FLUTTERFIRE OPTIONS
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint("Firebase Init Error: $e");
  }
  runApp(const IrisApp());
}

class IrisApp extends StatelessWidget {
  const IrisApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(colorSchemeSeed: Colors.deepPurple, brightness: Brightness.dark),
      home: const IrisVoiceDashboard(),
    );
  }
}

class IrisVoiceDashboard extends StatefulWidget {
  const IrisVoiceDashboard({super.key});
  @override
  State<IrisVoiceDashboard> createState() => _IrisVoiceDashboardState();
}

class _IrisVoiceDashboardState extends State<IrisVoiceDashboard> {
  final FlutterTts _tts = FlutterTts();
  final stt.SpeechToText _speech = stt.SpeechToText();
  final DatabaseReference _dbRef = FirebaseDatabase.instance.ref();

  String _systemStatus = "Tap the mic and say 'I want to see'";
  String _detectedWords = "";
  bool _isListening = false;

  @override
  void initState() {
    super.initState();
    _setupFirebaseListener();
  }

  // Listen for the Pi's text output responses
  void _setupFirebaseListener() {
    _dbRef.child('RaspberryString').onValue.listen((event) {
      String freshData = event.snapshot.value?.toString() ?? "";
      if (freshData.isNotEmpty && freshData != "TRIGGER") {
        setState(() {
          _systemStatus = freshData;
        });
        _tts.stop();
        _tts.speak(freshData);
      }
    });
  }

  // Triggered when user holds/taps the microphone button
  void _startVoiceListening() async {
    bool available = await _speech.initialize(
      onStatus: (status) => debugPrint('Speech Status: $status'),
      onError: (errorNotification) => debugPrint('Speech Error: $errorNotification'),
    );

    if (available) {
      setState(() => _isListening = true);
      _speech.listen(
        onResult: (result) {
          setState(() {
            _detectedWords = result.recognizedWords;
            // Check if the user said the magical words phrase
            if (_detectedWords.toLowerCase().contains("i want to see")) {
              _sendTriggerToPi();
            }
          });
        },
      );
    }
  }

  void _stopVoiceListening() {
    setState(() => _isListening = false);
    _speech.stop();
  }

  // Send the trigger command up to the Firebase node
  void _sendTriggerToPi() {
    _stopVoiceListening();
    setState(() {
      _systemStatus = "Sending request to Pi...";
    });
    // This alters the string value which the Pi is actively watching
    _dbRef.child('RaspberryString').set("TRIGGER");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('IRIS 2.0 Voice Hub'), centerTitle: true),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(24.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(_isListening ? "Listening..." : "System Status:", style: const TextStyle(color: Colors.grey)),
              const SizedBox(height: 10),
              Card(
                child: Padding(
                  padding: const EdgeInsets.all(20.0),
                  child: Text(_systemStatus, style: const TextStyle(fontSize: 22), textAlign: TextAlign.center),
                ),
              ),
              const SizedBox(height: 10),
              Text("Heard: '$_detectedWords'", style: const TextStyle(fontStyle: FontStyle.italic, color: Colors.deepPurpleAccent)),
              const SizedBox(height: 50),
              FloatingActionButton.large(
                onPressed: _isListening ? _stopVoiceListening : _startVoiceListening,
                backgroundColor: _isListening ? Colors.red : Colors.deepPurple,
                child: Icon(_isListening ? Icons.mic : Icons.mic_none, size: 40),
              ),
            ],
          ),
        ),
      ),
    );
  }
}